# Generated by Django 5.0.7 on 2024-09-16 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('sin_asignar', 'Sin asignar'), ('en_proceso', 'En proceso'), ('escalado', 'Escalado'), ('terminado', 'Terminado'), ('devuelto', 'Devuelto')], default='sin_asignar', max_length=20),
        ),
    ]
